export const words = ["veverička", "hlina", "silný", "miska", "list", "zima", "víno", "príliv", "divoký", "svit",
    "mimo", "film", "pisár", "briliant", "vlnitý", "vitamín", "klin", "limuzína", "disk", "simulátor",
    "militant", "bilión", "minúta", "limit",  "vírus", "mikrofón", "vizitka", "migrácia", "figúrka",
    "faktor", "divízia", "limitovať", "minister", "klimatizácia", "diplomat", "rituál", "kritik", "iniciatíva", "istota",
    "indián", "fiktívny", "inštitút", "indikátor", "infúzia", "pilier", "identita", "imigrácia", "ilustrácia", "infikovať",
    "imitácia", "investícia", "intuícia", "indukcia", "injekcia", "inšpirácia", "intervencia", "inštitúcia", "integrácia",
    "inovácia", "intimita", "imunita", "iluminácia", "inteligencia", "industrializácia", "individualita", "imperializmus", "iniciátor", "infraštruktúra",
    "imigrácia", "ilustrácia", "infikovať", "irigácia", "imitácia", "investícia", "intuícia", "indukcia", "injekcia", "inšpirácia",
    "intervencia", "inštitúcia", "integrácia", "inovácia", "intimita", "imunita", "iluminácia", "inteligencia", "industrializácia", "individualita",
    "imperializmus", "iniciátor", "infraštruktúra", "imigrácia", "ilustrácia", "infikovať", "irigácia", "imitácia", "investícia", "intuícia", "sýkorka", "korytnačka", "dyno", "zvyk", "rytmus", "syntéza", "lyžica", "fyzika", "pyramída", "systém",
    "typ", "kryštál", "dynamit", "krypta", "mytológia", "sympózium", "kybernetika", "hypotéza", "mýto", "ryba",
    "kyslík", "rys", "psychológia", "hydrodynamika", "mýdlo", "syntetizátor", "kyvadlo", "symbióza", "lyko", "mýtus",
    "syndikát", "šikana", "kyberšikana", "symfónia", "hypotéka", "kyselina", "rytmický", "mlyn", "symetria", "kyslý",
    "sypať", "kryštálový", "mýliť sa", "štýl", "syrový", "typický", "syr", "ryža", "myšlienka",
    "sylabus", "typografia", "mylný", "symptom", "synchrónny", "kývať", "kyprí", "mytológ", "synchronizácia", "sympatia",
    "kysnutie", "umývať", "symetrický", "synchronizér", "kyslí", "mýtus", "synergia", "kyselina",
    "sypať", "kryštálový", "mýliť"];
